### PR TITLE
remove cdn-viewer

### PR DESCRIPTION
**Pull request by ben-polinsky**
Remove cdn-viewer https://github.com/iTwin/itwinjs-backlog/issues/389

### CODE REVIEW

**Comment by aruniverse** [comment]
image

**Comment by ben-polinsky** [comment]
> i think you should also be able to delete the [cdn-test](https://github.com/iTwin/viewer/tree/master/packages/apps/cdn-viewer-test)

Should be gone?

**Comment by aruniverse** [comment]
as well as nuking the [ItwinViewer](https://github.com/iTwin/viewer/blob/master/packages/modules/web-viewer-react/src/services/ItwinViewer.ts) class and its test

**Comment by aruniverse** [comment]
> > i think you should also be able to delete the [cdn-test](https://github.com/iTwin/viewer/tree/master/packages/apps/cdn-viewer-test?rgh-link-date=2022-10-28T16%3A24%3A40Z)
> 
> Should be gone?

yep, my bad

**Comment by ben-polinsky** [comment]
Todo: Remove at 4.0 release

**Review by aruniverse — APPROVED** [review]

**Pull request merged**
